title: Business Insights Blog
description: Expert business analysis, trends, and strategies for success
url: https://happyvibess.github.io/business-blog
baseurl: "/business-blog"

# SEO settings
lang: en
author: happyvibess
twitter:
  username: happyvibess
logo: /assets/images/logo.png
social:
  name: Business Insights Blog
  links:
    - https://github.com/happyvibess
    - https://www.buymeacoffee.com/happyvibess

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Content settings
paginate: 10
paginate_path: "/page:num/"

# Analytics
google_analytics: UA-XXXXXXXX-X

# Comments
disqus:
  shortname: your-disqus-shortname

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  categories:
    output: true
    permalink: /category/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE

